In [49]:
import numpy as np
import math 

grid_size = (30, 15)
grid = np.zeros(grid_size)
agent_pos = (15,7)
grid[agent_pos]=8

# Generate n random indices
indices = np.random.randint(0, grid_size[0]*grid_size[1], size=10)
rows = indices // grid_size[1]
cols = indices % grid_size[1]

# Set the randomly selected elements to a certain number
value_to_set = -3  # Example value to set
for r, c in zip(rows, cols):
    if r!=6 and c!=3:
        grid[r, c] = value_to_set


def pixels_in_shadow():
       
        obstacle_map = np.where(grid == -3, 1, 0)

        obstacles = []
        for i in range(len(obstacle_map)):
            for j in range(len(obstacle_map[i])):
                if obstacle_map[i][j] == 1:
                    obstacles.append((i, j))
        
        # know we have a list with the obstacles positions, now for
        # each position i have tu calculate the ray of the shadow

        #print(obstacles)
        dark = []
        k=0.5 # coefficient to make the ray centered in the pixel
        for obstacle in obstacles: 

            if agent_pos[1]!=obstacle[1]:
                m = ((obstacle[0]+k) - (agent_pos[0]+k))/((obstacle[1]+k) - (agent_pos[1]+k))
                q = (agent_pos[0]+k)-(agent_pos[1]+k)*m

            if agent_pos[1]<obstacle[1]:

                for x in range(obstacle[1]+1,grid_size[1]):
                    xp = x+k
                    y = math.floor(m*xp+q)
                    if y<grid_size[0] and y>=0:                      
                        dark.append((y,x))
                
            if agent_pos[1]>obstacle[1]:

                for x in range(obstacle[1]-1,-1,-1):
                    xp = x+k
                    y = math.floor(m*xp+q)
                    if y<grid_size[0] and y>=0:                     
                        dark.append((y,x))

            if agent_pos[0]>obstacle[0] and agent_pos[1]==obstacle[1]:

                for y in range(obstacle[0]-1,-1,-1):
                    if y<grid_size[0] and y>=0:                  
                        dark.append((y,obstacle[1]))

            if agent_pos[0]<obstacle[0] and agent_pos[1]==obstacle[1]:

                for y in range(obstacle[0]+1,grid_size[0]):
                    dark.append((y,obstacle[1]))
        
        return dark

coordinate = pixels_in_shadow()

#print(grid)
print(coordinate)
for x, y in coordinate:
    grid[x][y] = 1

print(grid)

[(0, 11), (13, 13), (12, 14), (20, 3), (22, 2), (23, 1), (24, 0), (22, 7), (23, 7), (24, 7), (25, 7), (26, 7), (27, 7), (28, 7), (29, 7)]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -3. -3.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  

In [ ]:
        # def get_obs(self):
        #     offsets = [
        #         (-1, 0),    # N
        #         (0, 1),     # E
        #         (1, 0),     # S
        #         (0, -1),    # W
        #         (-1, 1),    # NE
        #         (1, 1),     # SE
        #         (1, -1),    # SW
        #         (-1, -1),   # NW 
        #         (-2, 0),    # NN
        #         (0, 2),     # EE
        #         (2, 0),     # SS
        #         (0, -2),    # WW
        #         (-2, 1),    # NNE
        #         (-1, 2),    # ENE
        #         (1, 2),     # ESE
        #         (2, 1),     # SSE
        #         (2, -1),    # SSW
        #         (1, -2),    # WSW
        #         (-1, -2),   # WNW
        #         (-2, -1),   # NNW
        #         (-3, 0),    # NNN
        #         (0, 3),     # EEE
        #         (3, 0),     # SSS
        #         (0, -3),    # WWW
        #         (-3, 1),    # NNNE
        #         (-2, 2),    # ENNE
        #         (-1, 3),    # EENE
        #         (1, 3),     # EESE
        #         (2, 2),     # ESSE
        #         (3, 1),     # SSEE
        #         (3, -1),    # SSWW
        #         (2, -2),    # WSWW
        #         (1, -3),    # WWNW
        #         (-1, -3),   # WWNE
        #         (-2, -2),   # WNWW
        #         (-3, -1),   # NNNW
        #         (-4, 0),    # NNNN
        #         (0, 4),     # EEEE
        #         (4, 0),     # SSSS
        #         (0, -4),    # WWWW
        #         (-4, 1),    # NNNNE
        #         (-3, 2),    # ENNNE
        #         (-2, 3),    # EENNE
        #         (-1, 4),    # EEESE
        #         (1, 4),     # EEENE
        #         (2, 3),     # EESSE
        #         (3, 2),     # SSEEE
        #         (4, 1),     # SSSSE
        #         (4, -1),    # SSSSW
        #         (3, -2),    # WSSSW
        #         (2, -3),    # WWSSW
        #         (1, -4),    # WWSWW
        #         (-1, -4),   # WWNWW
        #         (-2, -3),   # WWNNW
        #         (-3, -2),   # NNNWW
        #         (-4, -1),   # NNNNW
        #         (-5, 0),    # NNNNN
        #         (0, 5),     # EEEEE
        #         (5, 0),     # SSSSS
        #         (0, -5),    # WWWWW
        #     ]

In [ ]:
%tensorboard --logdir data/logs